import { Mission, Achievement, Quest } from './types';

export const MISSIONS: Mission[] = [
  // === RECON TIER (Beginner — foundational skills) ===
  {
    id: 'mission-12',
    title: 'CRUD Boot Camp',
    codename: 'BOOTCAMP',
    tier: 'recon',
    description: 'Master the fundamentals: insert, find, update, and delete documents under time pressure.',
    briefing: `WELCOME TO THE GRID\n\nEvery heist starts with the basics. Before you can crack compound queries or shard clusters, you need to master CRUD. Your mission: insert documents with insertOne and insertMany, query with find and findOne, update with updateOne and updateMany, and delete the evidence.\n\nThis is your proving ground, agent. Show us what you've got.`,
    objectives: [
      { id: 'obj-12-1', text: 'Insert a single document with insertOne()', completed: false },
      { id: 'obj-12-2', text: 'Bulk insert documents with insertMany()', completed: false },
      { id: 'obj-12-3', text: 'Query documents with find() and findOne()', completed: false },
      { id: 'obj-12-4', text: 'Update documents with updateOne() and $set', completed: false },
      { id: 'obj-12-5', text: 'Delete documents with deleteOne()', completed: false },
    ],
    timeLimit: 420,
    xpReward: 350,
    difficulty: 1,
    topic: 'query',
    povCapabilities: ['RICH-QUERY'],
    chaosEvents: [],
  },
  {
    id: 'mission-1',
    title: 'The Phantom Index',
    codename: 'PHANTOM',
    tier: 'recon',
    description: 'Diagnose why queries are running 100x slower than expected on a collection with 50 million documents.',
    briefing: `INCOMING TRANSMISSION...\n\nAgent, we've detected anomalous query latency on Collection ALPHA-7. Response times have spiked from 2ms to 15 seconds. The data pipeline is hemorrhaging. Intel suggests missing compound indexes — but something else is wrong. Your mission: analyze the explain() output, identify the collection scan, create the optimal index, and restore query performance before the pipeline collapses.\n\nTime is critical. Good luck.`,
    objectives: [
      { id: 'obj-1-1', text: 'Analyze the slow query explain() output', completed: false },
      { id: 'obj-1-2', text: 'Identify the missing compound index', completed: false },
      { id: 'obj-1-3', text: 'Create the optimal index strategy', completed: false },
      { id: 'obj-1-4', text: 'Verify query performance improvement', completed: false },
    ],
    timeLimit: 600,
    xpReward: 500,
    difficulty: 2,
    topic: 'query',
    povCapabilities: ['RICH-QUERY'],
    chaosEvents: [
      { id: 'chaos-1-1', title: '⚠ WRITE LOCK DETECTED', description: 'A background index build is blocking writes. Queries are queueing up!', triggerAt: 180, penalty: 100, duration: 60 },
    ],
  },
  {
    id: 'mission-3',
    title: 'The Aggregation Heist',
    codename: 'PIPELINE',
    tier: 'recon',
    description: 'Build a complex aggregation pipeline to extract critical intel from deeply nested documents.',
    briefing: `DECRYPTION COMPLETE\n\nWe've intercepted a data dump with 2 million nested documents. The intel is buried deep — nested arrays within arrays, polymorphic schemas, and no two documents are alike. Your mission: construct an aggregation pipeline using $unwind, $lookup, $facet, and $merge to extract the target data and prepare it for analysis.\n\nThe data self-destructs in 8 minutes.`,
    objectives: [
      { id: 'obj-3-1', text: 'Analyze the document schema structure', completed: false },
      { id: 'obj-3-2', text: 'Build the $unwind and $match stages', completed: false },
      { id: 'obj-3-3', text: 'Add $lookup for cross-collection joins', completed: false },
      { id: 'obj-3-4', text: 'Implement $facet for parallel aggregations', completed: false },
      { id: 'obj-3-5', text: 'Output results with $merge', completed: false },
    ],
    timeLimit: 480,
    xpReward: 750,
    difficulty: 3,
    topic: 'query',
    povCapabilities: ['IN-PLACE-ANALYTICS'],
    chaosEvents: [
      { id: 'chaos-3-1', title: '💾 MEMORY LIMIT HIT', description: 'Aggregation exceeding 100MB memory limit! Enable allowDiskUse or optimize.', triggerAt: 200, penalty: 100, duration: 45 },
    ],
  },
  {
    id: 'mission-6',
    title: 'Rich Query Recon',
    codename: 'RICHQUERY',
    tier: 'recon',
    description: 'Master compound queries with nested fields, array operators, projections, and compound indexes on 1M customer records.',
    briefing: `INTEL BRIEFING\n\nA customer database with 1 million insurance records needs to be queried efficiently. Your targets: female customers born in 1990, living in Utah, with life insurance policies where the insured person is a smoker.\n\nBuild compound queries with $elemMatch on nested arrays, add projections to reduce payload, sort and paginate results, then create the perfect compound index to prove IXSCAN.\n\nSpeed is everything. The data analysts are waiting.`,
    objectives: [
      { id: 'obj-6-1', text: 'Build compound find() with $elemMatch on nested arrays', completed: false },
      { id: 'obj-6-2', text: 'Add projections to return only needed fields', completed: false },
      { id: 'obj-6-3', text: 'Sort and paginate results with sort/limit/skip', completed: false },
      { id: 'obj-6-4', text: 'Create compound index and verify IXSCAN with explain()', completed: false },
    ],
    timeLimit: 480,
    xpReward: 600,
    difficulty: 2,
    topic: 'query',
    povCapabilities: ['RICH-QUERY'],
    chaosEvents: [
      { id: 'chaos-6-1', title: '📈 QUERY SPIKE', description: 'Another team just fired 10,000 concurrent queries! Collection scans are killing the cluster.', triggerAt: 150, penalty: 100, duration: 45 },
    ],
  },
  {
    id: 'mission-8',
    title: 'Analytics Extraction',
    codename: 'ANALYTICS',
    tier: 'recon',
    description: 'Run in-place analytics with aggregation pipelines while isolating workloads to protect production reads.',
    briefing: `DATA EXTRACTION REQUEST\n\nThe business team needs real-time revenue analytics — total, average, min, max by category and time period. But the CRUD workload on the primary is already at 80% capacity.\n\nYour mission: build aggregation pipelines for in-place analytics, group by time dimensions, and route analytics queries to secondary replicas using read preferences to achieve workload isolation.\n\nDon't let analytics kill production.`,
    objectives: [
      { id: 'obj-8-1', text: 'Build aggregation pipeline with $group and accumulators', completed: false },
      { id: 'obj-8-2', text: 'Add time-based grouping with $year/$month', completed: false },
      { id: 'obj-8-3', text: 'Configure read preference for workload isolation', completed: false },
    ],
    timeLimit: 420,
    xpReward: 550,
    difficulty: 2,
    topic: 'analytics',
    povCapabilities: ['IN-PLACE-ANALYTICS', 'WORKLOAD-ISOLATION'],
    chaosEvents: [
      { id: 'chaos-8-1', title: '📊 PIPELINE OVERFLOW', description: 'Aggregation is consuming too much memory! Consider allowDiskUse.', triggerAt: 180, penalty: 100, duration: 45 },
    ],
  },

  // === INFILTRATION TIER (Intermediate) ===
  {
    id: 'mission-13',
    title: 'Geospatial Pursuit',
    codename: 'GEOTRACK',
    tier: 'infiltration',
    description: 'Track assets across the globe using 2dsphere indexes, $geoNear, and $geoWithin on location data.',
    briefing: `GEOINT ALERT\n\nAssets are on the move. We have GPS coordinates for every operative and safe house in the network. Your mission: create 2dsphere indexes on location data, use $geoNear to find operatives within a radius of a target point, then use $geoWithin to identify all assets inside a defined polygon zone.\n\nEvery second they're moving. Lock onto their positions NOW.`,
    objectives: [
      { id: 'obj-13-1', text: 'Create a 2dsphere index on location field', completed: false },
      { id: 'obj-13-2', text: 'Use $geoNear to find locations within a radius', completed: false },
      { id: 'obj-13-3', text: 'Use $geoWithin with $geometry polygon', completed: false },
      { id: 'obj-13-4', text: 'Combine geo queries with other filters', completed: false },
    ],
    timeLimit: 600,
    xpReward: 800,
    difficulty: 3,
    topic: 'query',
    povCapabilities: ['GEOSPATIAL'],
    chaosEvents: [
      { id: 'chaos-13-1', title: '📡 GPS DRIFT', description: 'Satellite interference! Coordinates may be inaccurate by up to 500m.', triggerAt: 200, penalty: 150, duration: 60 },
    ],
  },
  {
    id: 'mission-14',
    title: 'Graph Infiltration',
    codename: 'GRAPHWEB',
    tier: 'infiltration',
    description: 'Traverse a social network graph with $graphLookup to uncover hidden connections and fraud rings.',
    briefing: `NETWORK ANALYSIS\n\nWe've mapped a suspected fraud ring through transaction patterns. The connections are buried in a social graph — friends of friends of friends. Your mission: use $graphLookup to traverse the relationship graph, find all connections up to 4 degrees of separation, detect cycles that indicate money laundering patterns.\n\nFollow the money. Find the ring.`,
    objectives: [
      { id: 'obj-14-1', text: 'Build $graphLookup to traverse connections', completed: false },
      { id: 'obj-14-2', text: 'Set maxDepth to limit traversal', completed: false },
      { id: 'obj-14-3', text: 'Filter results with restrictSearchWithMatch', completed: false },
      { id: 'obj-14-4', text: 'Identify fraud patterns in the graph output', completed: false },
    ],
    timeLimit: 600,
    xpReward: 850,
    difficulty: 3,
    topic: 'query',
    povCapabilities: ['GRAPH'],
    chaosEvents: [
      { id: 'chaos-14-1', title: '🕸️ RECURSIVE LOOP', description: 'Graph traversal hitting circular reference! Limit your depth or it will time out.', triggerAt: 250, penalty: 150, duration: 60 },
    ],
  },
  {
    id: 'mission-15',
    title: 'Change Stream Stakeout',
    codename: 'WIRETAP',
    tier: 'infiltration',
    description: 'Set up real-time change stream surveillance to detect and react to database mutations as they happen.',
    briefing: `SURVEILLANCE OPERATION\n\nWe need eyes on the transactions collection — real-time. Every insert, update, and delete must be captured and logged. Set up a change stream, filter for suspicious operations, and implement a resume token strategy so we never miss an event, even if the watcher crashes.\n\nThe targets don't know they're being watched. Keep it that way.`,
    objectives: [
      { id: 'obj-15-1', text: 'Open a change stream with collection.watch()', completed: false },
      { id: 'obj-15-2', text: 'Filter changes with $match pipeline', completed: false },
      { id: 'obj-15-3', text: 'Store and use resumeAfter token', completed: false },
      { id: 'obj-15-4', text: 'Handle change events by operationType', completed: false },
    ],
    timeLimit: 600,
    xpReward: 800,
    difficulty: 3,
    topic: 'data-management',
    povCapabilities: ['CHANGE-CAPTURE'],
    chaosEvents: [
      { id: 'chaos-15-1', title: '📡 STREAM DISCONNECTED', description: 'Change stream lost connection! Resume from the last token before events are lost.', triggerAt: 200, penalty: 150, duration: 60 },
    ],
  },
  {
    id: 'mission-16',
    title: 'Transaction Lockout',
    codename: 'ACIDRAIN',
    tier: 'infiltration',
    description: 'Execute multi-document ACID transactions to transfer funds atomically across accounts — no partial writes.',
    briefing: `CRITICAL TRANSFER\n\nFunds need to move between accounts atomically. If the debit succeeds but the credit fails, money vanishes. Your mission: start a session, begin a transaction, perform multiple writes across collections, and either commit all changes or abort everything.\n\nThere is no "partial success" in this operation.`,
    objectives: [
      { id: 'obj-16-1', text: 'Start a client session for transactions', completed: false },
      { id: 'obj-16-2', text: 'Begin transaction with readConcern/writeConcern', completed: false },
      { id: 'obj-16-3', text: 'Execute multi-document writes within the transaction', completed: false },
      { id: 'obj-16-4', text: 'Commit or abort the transaction', completed: false },
    ],
    timeLimit: 600,
    xpReward: 850,
    difficulty: 3,
    topic: 'data-management',
    povCapabilities: ['TRANSACTION'],
    chaosEvents: [
      { id: 'chaos-16-1', title: '🔒 WRITE CONFLICT', description: 'Another transaction modified the same document! Handle the conflict.', triggerAt: 250, penalty: 150, duration: 60 },
    ],
  },
  {
    id: 'mission-2',
    title: 'Shard Under Siege',
    codename: 'SIEGE',
    tier: 'infiltration',
    description: 'A shard is failing under load. Rebalance data across the cluster before total collapse.',
    briefing: `PRIORITY ONE ALERT\n\nShard rs2 is at 95% capacity and climbing. The chunk balancer has stalled, and data distribution is critically skewed. Three microservices are timing out. You need to manually trigger chunk migration, rebalance the shard key ranges, and stabilize the cluster — all while live traffic continues to flow.\n\nDo NOT let the shard go down.`,
    objectives: [
      { id: 'obj-2-1', text: 'Assess shard distribution with sh.status()', completed: false },
      { id: 'obj-2-2', text: 'Identify the hot shard and uneven chunk ranges', completed: false },
      { id: 'obj-2-3', text: 'Initiate manual chunk migration', completed: false },
      { id: 'obj-2-4', text: 'Verify balanced distribution across all shards', completed: false },
      { id: 'obj-2-5', text: 'Confirm all services are responding', completed: false },
    ],
    timeLimit: 900,
    xpReward: 1000,
    difficulty: 4,
    topic: 'scalability',
    povCapabilities: ['SCALE-OUT'],
    chaosEvents: [
      { id: 'chaos-2-1', title: '🔥 REPLICA SET MEMBER DOWN', description: 'Secondary member rs2-b has crashed! Failover in progress...', triggerAt: 240, penalty: 200, duration: 90 },
      { id: 'chaos-2-2', title: '⚡ NETWORK PARTITION', description: 'Network split detected between rs1 and rs2. Reads are failing!', triggerAt: 500, penalty: 150, duration: 60 },
    ],
  },
  {
    id: 'mission-4',
    title: 'Connection Storm',
    codename: 'STORM',
    tier: 'infiltration',
    description: 'Handle a sudden 10,000 connection spike without dropping a single request.',
    briefing: `SURGE DETECTED\n\nConnections are flooding in — 10,000 simultaneous clients hammering the cluster. Connection pools are maxed, the driver is throwing "pool exhausted" errors, and the application layer is starting to cascade fail. Configure connection pooling, implement retry logic, and set up proper timeout strategies before everything goes dark.\n\nEvery millisecond counts.`,
    objectives: [
      { id: 'obj-4-1', text: 'Diagnose connection pool exhaustion', completed: false },
      { id: 'obj-4-2', text: 'Configure optimal pool size settings', completed: false },
      { id: 'obj-4-3', text: 'Implement exponential backoff retry logic', completed: false },
      { id: 'obj-4-4', text: 'Set server selection and socket timeouts', completed: false },
    ],
    timeLimit: 720,
    xpReward: 850,
    difficulty: 3,
    topic: 'scalability',
    povCapabilities: ['CONSISTENCY'],
    chaosEvents: [
      { id: 'chaos-4-1', title: '🌊 SECOND WAVE INCOMING', description: 'Connection count doubled! Another 10K connections hitting the cluster!', triggerAt: 300, penalty: 200, duration: 120 },
    ],
  },
  {
    id: 'mission-9',
    title: 'Scale-Out Siege',
    codename: 'SCALEOUT',
    tier: 'infiltration',
    description: 'Shard a collection, sustain massive load, add shards dynamically, and verify data distributes evenly.',
    briefing: `CAPACITY CRITICAL\n\nThe events collection is growing at 10GB per hour. The single replica set is running out of disk and CPU. You must enable horizontal scaling: shard the collection with the right key, sustain load under pressure, add new shards to the cluster, and prove that the balancer distributes data evenly.\n\nScale or fail.`,
    objectives: [
      { id: 'obj-9-1', text: 'Enable sharding and choose shard key strategy', completed: false },
      { id: 'obj-9-2', text: 'Generate sustained write load', completed: false },
      { id: 'obj-9-3', text: 'Verify shard distribution is balanced', completed: false },
      { id: 'obj-9-4', text: 'Add a new shard to the cluster', completed: false },
    ],
    timeLimit: 720,
    xpReward: 900,
    difficulty: 3,
    topic: 'scalability',
    povCapabilities: ['SCALE-OUT'],
    chaosEvents: [
      { id: 'chaos-9-1', title: '💥 JUMBO CHUNKS', description: 'Chunk too large to migrate! Your shard key may have low cardinality.', triggerAt: 250, penalty: 200, duration: 90 },
    ],
  },
  {
    id: 'mission-10',
    title: 'Auto-HA Failover',
    codename: 'FAILOVER',
    tier: 'infiltration',
    description: 'Test automatic high availability: trigger failover and prove retryable writes make it transparent.',
    briefing: `HIGH AVAILABILITY DRILL\n\nCommand wants proof that our database survives primary failure. Your mission: connect without retryable writes and measure the downtime during failover. Then reconnect WITH retryable writes and prove zero visible disruption.\n\nTrigger the failover. Measure. Prove resilience.`,
    objectives: [
      { id: 'obj-10-1', text: 'Check replica set status and identify PRIMARY', completed: false },
      { id: 'obj-10-2', text: 'Connect without retryable writes (baseline)', completed: false },
      { id: 'obj-10-3', text: 'Enable retryable writes and reads', completed: false },
      { id: 'obj-10-4', text: 'Verify failover recovery is transparent', completed: false },
    ],
    timeLimit: 600,
    xpReward: 800,
    difficulty: 3,
    topic: 'operations',
    povCapabilities: ['AUTO-HA'],
    chaosEvents: [
      { id: 'chaos-10-1', title: '🔄 UNEXPECTED FAILOVER', description: 'The primary just stepped down! Was your app prepared?', triggerAt: 200, penalty: 150, duration: 60 },
    ],
  },

  // === EXFILTRATION TIER (Advanced) ===
  {
    id: 'mission-17',
    title: 'Text Search Infiltration',
    codename: 'SEARCHOPS',
    tier: 'exfiltration',
    description: 'Build Atlas Search indexes with fuzzy matching, autocomplete, and faceted search across document collections.',
    briefing: `SEARCH AND RECOVER\n\nIntelligence documents are scattered across millions of records. Keyword search isn't enough — you need fuzzy matching for misspellings, autocomplete for rapid identification, and faceted search to drill down by classification, date, and source.\n\nBuild the search infrastructure. Find the needle in the haystack.`,
    objectives: [
      { id: 'obj-17-1', text: 'Create an Atlas Search index with field mappings', completed: false },
      { id: 'obj-17-2', text: 'Build a $search query with fuzzy matching', completed: false },
      { id: 'obj-17-3', text: 'Implement autocomplete with edge n-gram', completed: false },
      { id: 'obj-17-4', text: 'Add faceted search with $searchMeta', completed: false },
    ],
    timeLimit: 720,
    xpReward: 1000,
    difficulty: 4,
    topic: 'query',
    povCapabilities: ['TEXT-SEARCH', 'AUTO-COMPLETE'],
    chaosEvents: [
      { id: 'chaos-17-1', title: '🔍 INDEX BUILDING', description: 'Search index is still building! Queries returning partial results.', triggerAt: 250, penalty: 150, duration: 90 },
    ],
  },
  {
    id: 'mission-5',
    title: 'The Schema Saboteur',
    codename: 'SABOTEUR',
    tier: 'exfiltration',
    description: 'Find and fix schema validation issues planted by a rogue insider across 5 collections.',
    briefing: `INSIDER THREAT CONFIRMED\n\nA rogue developer has sabotaged schema validation rules across 5 critical collections. Invalid documents are being inserted, data integrity is compromised, and downstream services are consuming corrupted data. Hunt down every tampered validation rule, restore proper JSON Schema validators, and ensure no more bad data gets through.\n\nTrust no document.`,
    objectives: [
      { id: 'obj-5-1', text: 'Audit all collection validators', completed: false },
      { id: 'obj-5-2', text: 'Identify tampered validation rules', completed: false },
      { id: 'obj-5-3', text: 'Fix validation on users collection', completed: false },
      { id: 'obj-5-4', text: 'Fix validation on transactions collection', completed: false },
      { id: 'obj-5-5', text: 'Fix validation on sessions collection', completed: false },
      { id: 'obj-5-6', text: 'Verify all validators reject invalid documents', completed: false },
    ],
    timeLimit: 1200,
    xpReward: 1500,
    difficulty: 5,
    topic: 'security',
    povCapabilities: ['SCHEMA'],
    chaosEvents: [
      { id: 'chaos-5-1', title: '🕵️ INSIDER STILL ACTIVE', description: 'The saboteur just changed another validator! Check the orders collection!', triggerAt: 400, penalty: 300, duration: 120 },
      { id: 'chaos-5-2', title: '📊 DATA CORRUPTION SPREADING', description: 'Invalid documents detected in analytics pipeline. Corruption rate: 23%', triggerAt: 700, penalty: 250, duration: 90 },
    ],
  },
  {
    id: 'mission-7',
    title: 'Encryption Lockdown',
    codename: 'CIPHER',
    tier: 'exfiltration',
    description: 'Implement Client-Side Field Level Encryption to protect PII data from database-level access.',
    briefing: `CLASSIFIED — EYES ONLY\n\nOur medical records database has been flagged by compliance. Patient SSNs and health data are stored in plaintext — visible to any DBA with cluster access. Your mission: implement CSFLE using envelope encryption.\n\nCreate a Customer Master Key in KMS, generate Data Encryption Keys, define the encryption schema, and prove that even with direct database access, the encrypted fields show only Binary ciphertext.\n\nNo plaintext. No exceptions.`,
    objectives: [
      { id: 'obj-7-1', text: 'Create Customer Master Key (CMK) in KMS', completed: false },
      { id: 'obj-7-2', text: 'Generate Data Encryption Key (DEK) with ClientEncryption', completed: false },
      { id: 'obj-7-3', text: 'Define encryption schema map with algorithms', completed: false },
      { id: 'obj-7-4', text: 'Create encrypted MongoClient with autoEncryption', completed: false },
      { id: 'obj-7-5', text: 'Insert and query — verify encryption/decryption works', completed: false },
    ],
    timeLimit: 900,
    xpReward: 1200,
    difficulty: 4,
    topic: 'encryption',
    povCapabilities: ['ENCRYPT-FIELDS', 'ENCRYPTION'],
    chaosEvents: [
      { id: 'chaos-7-1', title: '🔓 AUDIT ALERT', description: 'Compliance team running spot check! Encrypted fields must show Binary, not plaintext.', triggerAt: 300, penalty: 250, duration: 90 },
      { id: 'chaos-7-2', title: '🔑 KEY ROTATION REQUIRED', description: 'Security policy mandates key rotation. New DEK must be generated!', triggerAt: 600, penalty: 150, duration: 60 },
    ],
  },
  {
    id: 'mission-11',
    title: 'Deployment Automation',
    codename: 'TERRAFORM',
    tier: 'exfiltration',
    description: 'Automate Atlas cluster provisioning with Terraform — define, plan, and apply infrastructure as code.',
    briefing: `DEPLOYMENT ORDER\n\nManual cluster provisioning is over. Command wants infrastructure as code. Define a production-ready Atlas cluster in Terraform: specify the provider, region, instance size, and replication specs. Plan the deployment. Apply it. Verify the cluster is live.\n\nNo more clicking. Code the infrastructure.`,
    objectives: [
      { id: 'obj-11-1', text: 'Define Terraform resource for Atlas cluster', completed: false },
      { id: 'obj-11-2', text: 'Configure cluster specs (region, instance, replication)', completed: false },
      { id: 'obj-11-3', text: 'Run Terraform init/plan/apply commands', completed: false },
    ],
    timeLimit: 600,
    xpReward: 700,
    difficulty: 3,
    topic: 'deployment',
    povCapabilities: ['AUTO-DEPLOY', 'TERRAFORM'],
    chaosEvents: [
      { id: 'chaos-11-1', title: '🏗️ DRIFT DETECTED', description: 'Someone changed the cluster config manually! Your Terraform state is out of sync.', triggerAt: 250, penalty: 150, duration: 60 },
    ],
  },
];

// === QUEST CHAINS ===
export const QUESTS: Quest[] = [
  {
    id: 'quest-data-heist',
    title: 'The Data Heist',
    codename: 'OPERATION GENESIS',
    description: 'Master the complete MongoDB workflow — from basic CRUD to complex aggregations and indexing.',
    storyIntro: `OPERATION GENESIS\n\nAgent, this is your initiation into the MongoDB underground. You'll start with the basics — creating and querying documents. Then you'll graduate to compound queries, aggregation pipelines, and index optimization.\n\nComplete all four missions in sequence and you'll earn the "Genesis Agent" title and bonus XP.`,
    storyOutro: `OPERATION GENESIS COMPLETE\n\nYou've proven your mastery of MongoDB's core query engine. From simple CRUD to complex aggregation pipelines — you handled it all. The next operations will be harder. Rest up, agent.`,
    missionIds: ['mission-12', 'mission-6', 'mission-3', 'mission-1'],
    bonusXp: 500,
    icon: '🎯',
    requiredMissions: 4,
  },
  {
    id: 'quest-fortress',
    title: 'Fortress Protocol',
    codename: 'OPERATION FORTRESS',
    description: 'Secure the database from every angle — schema validation, encryption, and access control.',
    storyIntro: `OPERATION FORTRESS\n\nThe database is under siege. Rogue insiders, compliance auditors, and data thieves are all converging. Your mission chain: first lock down schema validation, then implement field-level encryption. Only agents who complete both earn the "Fortress Guardian" badge.`,
    storyOutro: `FORTRESS SECURED\n\nThe perimeter is locked down. Schema validation catches every invalid document. Field-level encryption ensures even DBAs can't read PII. The fortress holds.`,
    missionIds: ['mission-5', 'mission-7'],
    bonusXp: 750,
    icon: '🏰',
    requiredMissions: 2,
  },
  {
    id: 'quest-scale-wars',
    title: 'Scale Wars',
    codename: 'OPERATION HORIZON',
    description: 'Push MongoDB to its limits — connection storms, sharding, and horizontal scaling under fire.',
    storyIntro: `OPERATION HORIZON\n\nThe data is growing exponentially. Connections are spiking. The cluster needs to scale horizontally. This quest chain takes you through connection management, shard rebalancing, and full scale-out operations — all under chaos event pressure.`,
    storyOutro: `SCALE WARS WON\n\nFrom 10,000 connections to petabytes of sharded data — you scaled it all. The cluster is balanced, resilient, and ready for whatever comes next.`,
    missionIds: ['mission-4', 'mission-2', 'mission-9'],
    bonusXp: 600,
    icon: '⚔️',
    requiredMissions: 3,
  },
  {
    id: 'quest-intel-ops',
    title: 'Intelligence Operations',
    codename: 'OPERATION DARKNET',
    description: 'Advanced reconnaissance — geospatial tracking, graph analysis, and real-time surveillance.',
    storyIntro: `OPERATION DARKNET\n\nThe network is vast. Assets are scattered across the globe, connected through hidden relationships, and communicating in real-time. You'll need geospatial tracking, graph traversal, change stream surveillance, and full-text search to map the entire operation.`,
    storyOutro: `DARKNET EXPOSED\n\nEvery asset tracked. Every connection mapped. Every change captured in real-time. The intelligence network is fully operational.`,
    missionIds: ['mission-13', 'mission-14', 'mission-15', 'mission-17'],
    bonusXp: 800,
    icon: '🕵️',
    requiredMissions: 4,
  },
  {
    id: 'quest-full-stack',
    title: 'Full Stack Operative',
    codename: 'OPERATION OVERLORD',
    description: 'Complete every mission across all domains to prove you are the ultimate MongoDB operative.',
    storyIntro: `OPERATION OVERLORD\n\nThis is the final challenge. Complete EVERY mission in the system — query, encryption, analytics, scalability, operations, and deployment. Only the most dedicated agents earn the title of "Atlas Overlord."`,
    storyOutro: `OVERLORD STATUS ACHIEVED\n\nYou've completed every mission. Mastered every domain. Survived every chaos event. You are the Atlas Overlord. The grid bows to you.`,
    missionIds: MISSIONS.map(m => m.id),
    bonusXp: 2000,
    icon: '👑',
    requiredMissions: MISSIONS.length,
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'first-blood', name: 'First Blood', description: 'Complete your first mission', icon: '🩸', rarity: 'common', unlocked: false },
  { id: 'speed-demon', name: 'Speed Demon', description: 'Complete a mission in under 2 minutes', icon: '⚡', rarity: 'rare', unlocked: false },
  { id: 'chaos-survivor', name: 'Chaos Survivor', description: 'Complete a mission during a chaos event', icon: '🌪️', rarity: 'epic', unlocked: false },
  { id: 'full-collection', name: 'Full Collection', description: 'Complete all missions', icon: '🏆', rarity: 'legendary', unlocked: false },
  { id: 'perfect-run', name: 'Perfect Run', description: 'Complete a mission with all objectives and no penalties', icon: '💎', rarity: 'epic', unlocked: false },
  { id: 'recon-master', name: 'Recon Master', description: 'Complete all Recon tier missions', icon: '🔍', rarity: 'common', unlocked: false },
  { id: 'infiltrator', name: 'Infiltrator', description: 'Complete all Infiltration tier missions', icon: '🥷', rarity: 'rare', unlocked: false },
  { id: 'data-exfiltrator', name: 'Data Exfiltrator', description: 'Complete all Exfiltration tier missions', icon: '📡', rarity: 'epic', unlocked: false },
  { id: 'no-sleep', name: 'No Sleep Till Mongo', description: 'Play for over 60 minutes total', icon: '☕', rarity: 'common', unlocked: false },
  { id: 'index-everything', name: 'Index Everything', description: 'Complete The Phantom Index in under 3 minutes', icon: '📑', rarity: 'rare', unlocked: false },
  { id: 'cluster-whisperer', name: 'Cluster Whisperer', description: 'Survive 5 chaos events', icon: '🌀', rarity: 'epic', unlocked: false },
  { id: 'atlas-overlord', name: 'Atlas Overlord', description: 'Reach the highest rank', icon: '👑', rarity: 'legendary', unlocked: false },
  { id: 'query-ninja', name: 'Query Ninja', description: 'Complete Rich Query Recon without any hints', icon: '🥷', rarity: 'rare', unlocked: false },
  { id: 'crypto-agent', name: 'Crypto Agent', description: 'Complete Encryption Lockdown', icon: '🔐', rarity: 'epic', unlocked: false },
  { id: 'scale-master', name: 'Scale Master', description: 'Complete Scale-Out Siege', icon: '📐', rarity: 'rare', unlocked: false },
  { id: 'infra-coder', name: 'Infra as Code', description: 'Complete Deployment Automation', icon: '🏗️', rarity: 'epic', unlocked: false },
  { id: 'no-hints', name: 'No Training Wheels', description: 'Complete 3 missions on Expert difficulty', icon: '🎓', rarity: 'epic', unlocked: false },
  { id: 'hint-master', name: 'Hint Hunter', description: 'Reveal 20 hints across all missions', icon: '💡', rarity: 'common', unlocked: false },
  { id: 'quest-genesis', name: 'Genesis Agent', description: 'Complete The Data Heist quest chain', icon: '🎯', rarity: 'rare', unlocked: false },
  { id: 'quest-fortress', name: 'Fortress Guardian', description: 'Complete Fortress Protocol quest chain', icon: '🏰', rarity: 'epic', unlocked: false },
  { id: 'quest-overlord', name: 'Full Stack Operative', description: 'Complete Operation Overlord quest', icon: '👑', rarity: 'legendary', unlocked: false },
  { id: 'geo-tracker', name: 'Geo Tracker', description: 'Complete Geospatial Pursuit', icon: '🗺️', rarity: 'rare', unlocked: false },
  { id: 'graph-detective', name: 'Graph Detective', description: 'Complete Graph Infiltration', icon: '🕸️', rarity: 'rare', unlocked: false },
  { id: 'wire-tapper', name: 'Wire Tapper', description: 'Complete Change Stream Stakeout', icon: '📡', rarity: 'rare', unlocked: false },
];

export const RANK_THRESHOLDS: { rank: string; minXP: number }[] = [
  { rank: 'Script Kiddie', minXP: 0 },
  { rank: 'Query Cadet', minXP: 500 },
  { rank: 'Replica Ranger', minXP: 1500 },
  { rank: 'Shard Commander', minXP: 3000 },
  { rank: 'Atlas Overlord', minXP: 5000 },
];

export const HACKER_ADJECTIVES = [
  'Shadow', 'Phantom', 'Cyber', 'Null', 'Binary', 'Rogue', 'Ghost', 'Neon',
  'Quantum', 'Stealth', 'Dark', 'Zero', 'Void', 'Glitch', 'Vector',
];

export const HACKER_NOUNS = [
  'Mongoose', 'Cursor', 'Shard', 'Replica', 'Pipeline', 'Atlas', 'Cluster',
  'Index', 'Document', 'Schema', 'Query', 'Oplog', 'Chunk', 'Node', 'Driver',
];

export function generateHandle(): string {
  const adj = HACKER_ADJECTIVES[Math.floor(Math.random() * HACKER_ADJECTIVES.length)];
  const noun = HACKER_NOUNS[Math.floor(Math.random() * HACKER_NOUNS.length)];
  const num = Math.floor(Math.random() * 99);
  return `${adj}${noun}${num}`;
}

export const MOCK_LEADERBOARD_PLAYERS = [
  { handle: 'PhantomShard42', xp: 4850, totalScore: 12400, completedMissions: 5, chaosEventsSurvived: 7 },
  { handle: 'CyberCursor99', xp: 4200, totalScore: 10800, completedMissions: 4, chaosEventsSurvived: 5 },
  { handle: 'NullPipeline7', xp: 3600, totalScore: 9200, completedMissions: 4, chaosEventsSurvived: 4 },
  { handle: 'GhostIndex33', xp: 3100, totalScore: 7900, completedMissions: 3, chaosEventsSurvived: 3 },
  { handle: 'VoidReplica88', xp: 2800, totalScore: 7100, completedMissions: 3, chaosEventsSurvived: 2 },
  { handle: 'StealthQuery56', xp: 2200, totalScore: 5600, completedMissions: 2, chaosEventsSurvived: 3 },
  { handle: 'DarkCluster11', xp: 1800, totalScore: 4500, completedMissions: 2, chaosEventsSurvived: 1 },
  { handle: 'NeonSchema77', xp: 1200, totalScore: 3000, completedMissions: 1, chaosEventsSurvived: 1 },
];